name: Release Tagging

on: [push]

jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: Check conventional commit compliance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@v3
