name: Release Tagging

on:
  push:
    branches:
      - main

jobs:
  release_job:
    runs-on: ubuntu-latest
    name: Perform release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cocogitto release
        id: release
        uses: oknozor/cocogitto-action@v2
        with:
          release: true

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Upload GitHub release 
        uses: softprops/action-gh-release@v1
        with:
          body: CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}
