name: Release Tagging

on:
  push:
    branches:
      - main

jobs:
  release_job:
    runs-on: ubuntu-latest
    name: Perform release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cocogitto release
        id: release
        uses: oknozor/cocogitto-action@v2
        with:
          release: true

      # - name: Generate Changelog
      #   run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md

      - name: Upload GitHub release 
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release.outputs.version }}
