name: Release Tagging

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'main'

      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@v3