name: Release Tagging

on:
  schedule:
    - cron: '51 13 * * *'

jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: Check conventional commit compliance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@v3
