name: Release Tagging

on: [push]

release:
  name: Perform release
    - uses: actions/checkout@v2
        with:
          fetch-depth: 0

    - name: Cocogitto release
      id: release
      uses: oknozor/cocogitto-action@v2
      with:
        release: true
          git-user: 'Cog Bot'
          git-user-email: 'mycoolproject@org.org'

    - name: Generate Changelog
      run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md

    - name: Upload github release
      uses: softprops/action-gh-release@v1
      with:
        body_path: GITHUB_CHANGELOG.md
        tag_name: ${{ steps.release.outputs.version }}
