name: Release Tagging

on: [push]

jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: Check conventional commit compliance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: SemVer Release
        uses: cocogitto/cocogitto-action@main
